services:
    postgres:
        image: postgres:17.4-alpine
        container_name: content-audit-db
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=content-audit
            - POSTGRES_PASSWORD=content-audit
            - POSTGRES_DB=content-audit
        volumes:
            - postgres-data:/var/lib/postgresql/data
        command: [ "postgres", "-c", "log_statement=all", "-N", "500", '-c', 'enable_incremental_sort=on']
        healthcheck:
          test: ["CMD-SHELL", "pg_isready -U content-audit"]
          interval: 10s
          timeout: 5s
          retries: 5
volumes:
    postgres-data:
        driver: local