
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `audit_page_run` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model audit_page_run
 * Represents an audit run against a particular page
 */
export type audit_page_runModel = runtime.Types.Result.DefaultSelection<Prisma.$audit_page_runPayload>

export type AggregateAudit_page_run = {
  _count: Audit_page_runCountAggregateOutputType | null
  _avg: Audit_page_runAvgAggregateOutputType | null
  _sum: Audit_page_runSumAggregateOutputType | null
  _min: Audit_page_runMinAggregateOutputType | null
  _max: Audit_page_runMaxAggregateOutputType | null
}

export type Audit_page_runAvgAggregateOutputType = {
  id: number | null
}

export type Audit_page_runSumAggregateOutputType = {
  id: number | null
}

export type Audit_page_runMinAggregateOutputType = {
  id: number | null
  created_at: Date | null
  url: string | null
}

export type Audit_page_runMaxAggregateOutputType = {
  id: number | null
  created_at: Date | null
  url: string | null
}

export type Audit_page_runCountAggregateOutputType = {
  id: number
  created_at: number
  url: number
  _all: number
}


export type Audit_page_runAvgAggregateInputType = {
  id?: true
}

export type Audit_page_runSumAggregateInputType = {
  id?: true
}

export type Audit_page_runMinAggregateInputType = {
  id?: true
  created_at?: true
  url?: true
}

export type Audit_page_runMaxAggregateInputType = {
  id?: true
  created_at?: true
  url?: true
}

export type Audit_page_runCountAggregateInputType = {
  id?: true
  created_at?: true
  url?: true
  _all?: true
}

export type Audit_page_runAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which audit_page_run to aggregate.
   */
  where?: Prisma.audit_page_runWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of audit_page_runs to fetch.
   */
  orderBy?: Prisma.audit_page_runOrderByWithRelationInput | Prisma.audit_page_runOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.audit_page_runWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` audit_page_runs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` audit_page_runs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned audit_page_runs
  **/
  _count?: true | Audit_page_runCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: Audit_page_runAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: Audit_page_runSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Audit_page_runMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Audit_page_runMaxAggregateInputType
}

export type GetAudit_page_runAggregateType<T extends Audit_page_runAggregateArgs> = {
      [P in keyof T & keyof AggregateAudit_page_run]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAudit_page_run[P]>
    : Prisma.GetScalarType<T[P], AggregateAudit_page_run[P]>
}




export type audit_page_runGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.audit_page_runWhereInput
  orderBy?: Prisma.audit_page_runOrderByWithAggregationInput | Prisma.audit_page_runOrderByWithAggregationInput[]
  by: Prisma.Audit_page_runScalarFieldEnum[] | Prisma.Audit_page_runScalarFieldEnum
  having?: Prisma.audit_page_runScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Audit_page_runCountAggregateInputType | true
  _avg?: Audit_page_runAvgAggregateInputType
  _sum?: Audit_page_runSumAggregateInputType
  _min?: Audit_page_runMinAggregateInputType
  _max?: Audit_page_runMaxAggregateInputType
}

export type Audit_page_runGroupByOutputType = {
  id: number
  created_at: Date | null
  url: string | null
  _count: Audit_page_runCountAggregateOutputType | null
  _avg: Audit_page_runAvgAggregateOutputType | null
  _sum: Audit_page_runSumAggregateOutputType | null
  _min: Audit_page_runMinAggregateOutputType | null
  _max: Audit_page_runMaxAggregateOutputType | null
}

type GetAudit_page_runGroupByPayload<T extends audit_page_runGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Audit_page_runGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Audit_page_runGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Audit_page_runGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Audit_page_runGroupByOutputType[P]>
      }
    >
  >



export type audit_page_runWhereInput = {
  AND?: Prisma.audit_page_runWhereInput | Prisma.audit_page_runWhereInput[]
  OR?: Prisma.audit_page_runWhereInput[]
  NOT?: Prisma.audit_page_runWhereInput | Prisma.audit_page_runWhereInput[]
  id?: Prisma.IntFilter<"audit_page_run"> | number
  created_at?: Prisma.DateTimeNullableFilter<"audit_page_run"> | Date | string | null
  url?: Prisma.StringNullableFilter<"audit_page_run"> | string | null
}

export type audit_page_runOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  created_at?: Prisma.SortOrderInput | Prisma.SortOrder
  url?: Prisma.SortOrderInput | Prisma.SortOrder
}

export type audit_page_runWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.audit_page_runWhereInput | Prisma.audit_page_runWhereInput[]
  OR?: Prisma.audit_page_runWhereInput[]
  NOT?: Prisma.audit_page_runWhereInput | Prisma.audit_page_runWhereInput[]
  created_at?: Prisma.DateTimeNullableFilter<"audit_page_run"> | Date | string | null
  url?: Prisma.StringNullableFilter<"audit_page_run"> | string | null
}, "id">

export type audit_page_runOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  created_at?: Prisma.SortOrderInput | Prisma.SortOrder
  url?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.audit_page_runCountOrderByAggregateInput
  _avg?: Prisma.audit_page_runAvgOrderByAggregateInput
  _max?: Prisma.audit_page_runMaxOrderByAggregateInput
  _min?: Prisma.audit_page_runMinOrderByAggregateInput
  _sum?: Prisma.audit_page_runSumOrderByAggregateInput
}

export type audit_page_runScalarWhereWithAggregatesInput = {
  AND?: Prisma.audit_page_runScalarWhereWithAggregatesInput | Prisma.audit_page_runScalarWhereWithAggregatesInput[]
  OR?: Prisma.audit_page_runScalarWhereWithAggregatesInput[]
  NOT?: Prisma.audit_page_runScalarWhereWithAggregatesInput | Prisma.audit_page_runScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"audit_page_run"> | number
  created_at?: Prisma.DateTimeNullableWithAggregatesFilter<"audit_page_run"> | Date | string | null
  url?: Prisma.StringNullableWithAggregatesFilter<"audit_page_run"> | string | null
}

export type audit_page_runCreateInput = {
  created_at?: Date | string | null
  url?: string | null
}

export type audit_page_runUncheckedCreateInput = {
  id?: number
  created_at?: Date | string | null
  url?: string | null
}

export type audit_page_runUpdateInput = {
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type audit_page_runUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type audit_page_runCreateManyInput = {
  id?: number
  created_at?: Date | string | null
  url?: string | null
}

export type audit_page_runUpdateManyMutationInput = {
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type audit_page_runUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type audit_page_runCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  url?: Prisma.SortOrder
}

export type audit_page_runAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type audit_page_runMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  url?: Prisma.SortOrder
}

export type audit_page_runMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  url?: Prisma.SortOrder
}

export type audit_page_runSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}



export type audit_page_runSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  created_at?: boolean
  url?: boolean
}, ExtArgs["result"]["audit_page_run"]>

export type audit_page_runSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  created_at?: boolean
  url?: boolean
}, ExtArgs["result"]["audit_page_run"]>

export type audit_page_runSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  created_at?: boolean
  url?: boolean
}, ExtArgs["result"]["audit_page_run"]>

export type audit_page_runSelectScalar = {
  id?: boolean
  created_at?: boolean
  url?: boolean
}

export type audit_page_runOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "created_at" | "url", ExtArgs["result"]["audit_page_run"]>

export type $audit_page_runPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "audit_page_run"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    created_at: Date | null
    /**
     * The URL of the page that ran
     */
    url: string | null
  }, ExtArgs["result"]["audit_page_run"]>
  composites: {}
}

export type audit_page_runGetPayload<S extends boolean | null | undefined | audit_page_runDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$audit_page_runPayload, S>

export type audit_page_runCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<audit_page_runFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Audit_page_runCountAggregateInputType | true
  }

export interface audit_page_runDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['audit_page_run'], meta: { name: 'audit_page_run' } }
  /**
   * Find zero or one Audit_page_run that matches the filter.
   * @param {audit_page_runFindUniqueArgs} args - Arguments to find a Audit_page_run
   * @example
   * // Get one Audit_page_run
   * const audit_page_run = await prisma.audit_page_run.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends audit_page_runFindUniqueArgs>(args: Prisma.SelectSubset<T, audit_page_runFindUniqueArgs<ExtArgs>>): Prisma.Prisma__audit_page_runClient<runtime.Types.Result.GetResult<Prisma.$audit_page_runPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Audit_page_run that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {audit_page_runFindUniqueOrThrowArgs} args - Arguments to find a Audit_page_run
   * @example
   * // Get one Audit_page_run
   * const audit_page_run = await prisma.audit_page_run.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends audit_page_runFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, audit_page_runFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__audit_page_runClient<runtime.Types.Result.GetResult<Prisma.$audit_page_runPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Audit_page_run that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {audit_page_runFindFirstArgs} args - Arguments to find a Audit_page_run
   * @example
   * // Get one Audit_page_run
   * const audit_page_run = await prisma.audit_page_run.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends audit_page_runFindFirstArgs>(args?: Prisma.SelectSubset<T, audit_page_runFindFirstArgs<ExtArgs>>): Prisma.Prisma__audit_page_runClient<runtime.Types.Result.GetResult<Prisma.$audit_page_runPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Audit_page_run that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {audit_page_runFindFirstOrThrowArgs} args - Arguments to find a Audit_page_run
   * @example
   * // Get one Audit_page_run
   * const audit_page_run = await prisma.audit_page_run.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends audit_page_runFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, audit_page_runFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__audit_page_runClient<runtime.Types.Result.GetResult<Prisma.$audit_page_runPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Audit_page_runs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {audit_page_runFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Audit_page_runs
   * const audit_page_runs = await prisma.audit_page_run.findMany()
   * 
   * // Get first 10 Audit_page_runs
   * const audit_page_runs = await prisma.audit_page_run.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const audit_page_runWithIdOnly = await prisma.audit_page_run.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends audit_page_runFindManyArgs>(args?: Prisma.SelectSubset<T, audit_page_runFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$audit_page_runPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Audit_page_run.
   * @param {audit_page_runCreateArgs} args - Arguments to create a Audit_page_run.
   * @example
   * // Create one Audit_page_run
   * const Audit_page_run = await prisma.audit_page_run.create({
   *   data: {
   *     // ... data to create a Audit_page_run
   *   }
   * })
   * 
   */
  create<T extends audit_page_runCreateArgs>(args: Prisma.SelectSubset<T, audit_page_runCreateArgs<ExtArgs>>): Prisma.Prisma__audit_page_runClient<runtime.Types.Result.GetResult<Prisma.$audit_page_runPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Audit_page_runs.
   * @param {audit_page_runCreateManyArgs} args - Arguments to create many Audit_page_runs.
   * @example
   * // Create many Audit_page_runs
   * const audit_page_run = await prisma.audit_page_run.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends audit_page_runCreateManyArgs>(args?: Prisma.SelectSubset<T, audit_page_runCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Audit_page_runs and returns the data saved in the database.
   * @param {audit_page_runCreateManyAndReturnArgs} args - Arguments to create many Audit_page_runs.
   * @example
   * // Create many Audit_page_runs
   * const audit_page_run = await prisma.audit_page_run.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Audit_page_runs and only return the `id`
   * const audit_page_runWithIdOnly = await prisma.audit_page_run.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends audit_page_runCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, audit_page_runCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$audit_page_runPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Audit_page_run.
   * @param {audit_page_runDeleteArgs} args - Arguments to delete one Audit_page_run.
   * @example
   * // Delete one Audit_page_run
   * const Audit_page_run = await prisma.audit_page_run.delete({
   *   where: {
   *     // ... filter to delete one Audit_page_run
   *   }
   * })
   * 
   */
  delete<T extends audit_page_runDeleteArgs>(args: Prisma.SelectSubset<T, audit_page_runDeleteArgs<ExtArgs>>): Prisma.Prisma__audit_page_runClient<runtime.Types.Result.GetResult<Prisma.$audit_page_runPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Audit_page_run.
   * @param {audit_page_runUpdateArgs} args - Arguments to update one Audit_page_run.
   * @example
   * // Update one Audit_page_run
   * const audit_page_run = await prisma.audit_page_run.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends audit_page_runUpdateArgs>(args: Prisma.SelectSubset<T, audit_page_runUpdateArgs<ExtArgs>>): Prisma.Prisma__audit_page_runClient<runtime.Types.Result.GetResult<Prisma.$audit_page_runPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Audit_page_runs.
   * @param {audit_page_runDeleteManyArgs} args - Arguments to filter Audit_page_runs to delete.
   * @example
   * // Delete a few Audit_page_runs
   * const { count } = await prisma.audit_page_run.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends audit_page_runDeleteManyArgs>(args?: Prisma.SelectSubset<T, audit_page_runDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Audit_page_runs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {audit_page_runUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Audit_page_runs
   * const audit_page_run = await prisma.audit_page_run.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends audit_page_runUpdateManyArgs>(args: Prisma.SelectSubset<T, audit_page_runUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Audit_page_runs and returns the data updated in the database.
   * @param {audit_page_runUpdateManyAndReturnArgs} args - Arguments to update many Audit_page_runs.
   * @example
   * // Update many Audit_page_runs
   * const audit_page_run = await prisma.audit_page_run.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Audit_page_runs and only return the `id`
   * const audit_page_runWithIdOnly = await prisma.audit_page_run.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends audit_page_runUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, audit_page_runUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$audit_page_runPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Audit_page_run.
   * @param {audit_page_runUpsertArgs} args - Arguments to update or create a Audit_page_run.
   * @example
   * // Update or create a Audit_page_run
   * const audit_page_run = await prisma.audit_page_run.upsert({
   *   create: {
   *     // ... data to create a Audit_page_run
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Audit_page_run we want to update
   *   }
   * })
   */
  upsert<T extends audit_page_runUpsertArgs>(args: Prisma.SelectSubset<T, audit_page_runUpsertArgs<ExtArgs>>): Prisma.Prisma__audit_page_runClient<runtime.Types.Result.GetResult<Prisma.$audit_page_runPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Audit_page_runs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {audit_page_runCountArgs} args - Arguments to filter Audit_page_runs to count.
   * @example
   * // Count the number of Audit_page_runs
   * const count = await prisma.audit_page_run.count({
   *   where: {
   *     // ... the filter for the Audit_page_runs we want to count
   *   }
   * })
  **/
  count<T extends audit_page_runCountArgs>(
    args?: Prisma.Subset<T, audit_page_runCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Audit_page_runCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Audit_page_run.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Audit_page_runAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Audit_page_runAggregateArgs>(args: Prisma.Subset<T, Audit_page_runAggregateArgs>): Prisma.PrismaPromise<GetAudit_page_runAggregateType<T>>

  /**
   * Group by Audit_page_run.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {audit_page_runGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends audit_page_runGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: audit_page_runGroupByArgs['orderBy'] }
      : { orderBy?: audit_page_runGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, audit_page_runGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAudit_page_runGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the audit_page_run model
 */
readonly fields: audit_page_runFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for audit_page_run.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__audit_page_runClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the audit_page_run model
 */
export interface audit_page_runFieldRefs {
  readonly id: Prisma.FieldRef<"audit_page_run", 'Int'>
  readonly created_at: Prisma.FieldRef<"audit_page_run", 'DateTime'>
  readonly url: Prisma.FieldRef<"audit_page_run", 'String'>
}
    

// Custom InputTypes
/**
 * audit_page_run findUnique
 */
export type audit_page_runFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the audit_page_run
   */
  select?: Prisma.audit_page_runSelect<ExtArgs> | null
  /**
   * Omit specific fields from the audit_page_run
   */
  omit?: Prisma.audit_page_runOmit<ExtArgs> | null
  /**
   * Filter, which audit_page_run to fetch.
   */
  where: Prisma.audit_page_runWhereUniqueInput
}

/**
 * audit_page_run findUniqueOrThrow
 */
export type audit_page_runFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the audit_page_run
   */
  select?: Prisma.audit_page_runSelect<ExtArgs> | null
  /**
   * Omit specific fields from the audit_page_run
   */
  omit?: Prisma.audit_page_runOmit<ExtArgs> | null
  /**
   * Filter, which audit_page_run to fetch.
   */
  where: Prisma.audit_page_runWhereUniqueInput
}

/**
 * audit_page_run findFirst
 */
export type audit_page_runFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the audit_page_run
   */
  select?: Prisma.audit_page_runSelect<ExtArgs> | null
  /**
   * Omit specific fields from the audit_page_run
   */
  omit?: Prisma.audit_page_runOmit<ExtArgs> | null
  /**
   * Filter, which audit_page_run to fetch.
   */
  where?: Prisma.audit_page_runWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of audit_page_runs to fetch.
   */
  orderBy?: Prisma.audit_page_runOrderByWithRelationInput | Prisma.audit_page_runOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for audit_page_runs.
   */
  cursor?: Prisma.audit_page_runWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` audit_page_runs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` audit_page_runs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of audit_page_runs.
   */
  distinct?: Prisma.Audit_page_runScalarFieldEnum | Prisma.Audit_page_runScalarFieldEnum[]
}

/**
 * audit_page_run findFirstOrThrow
 */
export type audit_page_runFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the audit_page_run
   */
  select?: Prisma.audit_page_runSelect<ExtArgs> | null
  /**
   * Omit specific fields from the audit_page_run
   */
  omit?: Prisma.audit_page_runOmit<ExtArgs> | null
  /**
   * Filter, which audit_page_run to fetch.
   */
  where?: Prisma.audit_page_runWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of audit_page_runs to fetch.
   */
  orderBy?: Prisma.audit_page_runOrderByWithRelationInput | Prisma.audit_page_runOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for audit_page_runs.
   */
  cursor?: Prisma.audit_page_runWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` audit_page_runs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` audit_page_runs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of audit_page_runs.
   */
  distinct?: Prisma.Audit_page_runScalarFieldEnum | Prisma.Audit_page_runScalarFieldEnum[]
}

/**
 * audit_page_run findMany
 */
export type audit_page_runFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the audit_page_run
   */
  select?: Prisma.audit_page_runSelect<ExtArgs> | null
  /**
   * Omit specific fields from the audit_page_run
   */
  omit?: Prisma.audit_page_runOmit<ExtArgs> | null
  /**
   * Filter, which audit_page_runs to fetch.
   */
  where?: Prisma.audit_page_runWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of audit_page_runs to fetch.
   */
  orderBy?: Prisma.audit_page_runOrderByWithRelationInput | Prisma.audit_page_runOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing audit_page_runs.
   */
  cursor?: Prisma.audit_page_runWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` audit_page_runs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` audit_page_runs.
   */
  skip?: number
  distinct?: Prisma.Audit_page_runScalarFieldEnum | Prisma.Audit_page_runScalarFieldEnum[]
}

/**
 * audit_page_run create
 */
export type audit_page_runCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the audit_page_run
   */
  select?: Prisma.audit_page_runSelect<ExtArgs> | null
  /**
   * Omit specific fields from the audit_page_run
   */
  omit?: Prisma.audit_page_runOmit<ExtArgs> | null
  /**
   * The data needed to create a audit_page_run.
   */
  data?: Prisma.XOR<Prisma.audit_page_runCreateInput, Prisma.audit_page_runUncheckedCreateInput>
}

/**
 * audit_page_run createMany
 */
export type audit_page_runCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many audit_page_runs.
   */
  data: Prisma.audit_page_runCreateManyInput | Prisma.audit_page_runCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * audit_page_run createManyAndReturn
 */
export type audit_page_runCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the audit_page_run
   */
  select?: Prisma.audit_page_runSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the audit_page_run
   */
  omit?: Prisma.audit_page_runOmit<ExtArgs> | null
  /**
   * The data used to create many audit_page_runs.
   */
  data: Prisma.audit_page_runCreateManyInput | Prisma.audit_page_runCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * audit_page_run update
 */
export type audit_page_runUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the audit_page_run
   */
  select?: Prisma.audit_page_runSelect<ExtArgs> | null
  /**
   * Omit specific fields from the audit_page_run
   */
  omit?: Prisma.audit_page_runOmit<ExtArgs> | null
  /**
   * The data needed to update a audit_page_run.
   */
  data: Prisma.XOR<Prisma.audit_page_runUpdateInput, Prisma.audit_page_runUncheckedUpdateInput>
  /**
   * Choose, which audit_page_run to update.
   */
  where: Prisma.audit_page_runWhereUniqueInput
}

/**
 * audit_page_run updateMany
 */
export type audit_page_runUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update audit_page_runs.
   */
  data: Prisma.XOR<Prisma.audit_page_runUpdateManyMutationInput, Prisma.audit_page_runUncheckedUpdateManyInput>
  /**
   * Filter which audit_page_runs to update
   */
  where?: Prisma.audit_page_runWhereInput
  /**
   * Limit how many audit_page_runs to update.
   */
  limit?: number
}

/**
 * audit_page_run updateManyAndReturn
 */
export type audit_page_runUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the audit_page_run
   */
  select?: Prisma.audit_page_runSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the audit_page_run
   */
  omit?: Prisma.audit_page_runOmit<ExtArgs> | null
  /**
   * The data used to update audit_page_runs.
   */
  data: Prisma.XOR<Prisma.audit_page_runUpdateManyMutationInput, Prisma.audit_page_runUncheckedUpdateManyInput>
  /**
   * Filter which audit_page_runs to update
   */
  where?: Prisma.audit_page_runWhereInput
  /**
   * Limit how many audit_page_runs to update.
   */
  limit?: number
}

/**
 * audit_page_run upsert
 */
export type audit_page_runUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the audit_page_run
   */
  select?: Prisma.audit_page_runSelect<ExtArgs> | null
  /**
   * Omit specific fields from the audit_page_run
   */
  omit?: Prisma.audit_page_runOmit<ExtArgs> | null
  /**
   * The filter to search for the audit_page_run to update in case it exists.
   */
  where: Prisma.audit_page_runWhereUniqueInput
  /**
   * In case the audit_page_run found by the `where` argument doesn't exist, create a new audit_page_run with this data.
   */
  create: Prisma.XOR<Prisma.audit_page_runCreateInput, Prisma.audit_page_runUncheckedCreateInput>
  /**
   * In case the audit_page_run was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.audit_page_runUpdateInput, Prisma.audit_page_runUncheckedUpdateInput>
}

/**
 * audit_page_run delete
 */
export type audit_page_runDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the audit_page_run
   */
  select?: Prisma.audit_page_runSelect<ExtArgs> | null
  /**
   * Omit specific fields from the audit_page_run
   */
  omit?: Prisma.audit_page_runOmit<ExtArgs> | null
  /**
   * Filter which audit_page_run to delete.
   */
  where: Prisma.audit_page_runWhereUniqueInput
}

/**
 * audit_page_run deleteMany
 */
export type audit_page_runDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which audit_page_runs to delete
   */
  where?: Prisma.audit_page_runWhereInput
  /**
   * Limit how many audit_page_runs to delete.
   */
  limit?: number
}

/**
 * audit_page_run without action
 */
export type audit_page_runDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the audit_page_run
   */
  select?: Prisma.audit_page_runSelect<ExtArgs> | null
  /**
   * Omit specific fields from the audit_page_run
   */
  omit?: Prisma.audit_page_runOmit<ExtArgs> | null
}
